# Generated by Django 2.1.2 on 2019-02-06 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='url',
            name='count',
            field=models.IntegerField(default=1, verbose_name='Amount of requests'),
        ),
        migrations.AlterField(
            model_name='url',
            name='link',
            field=models.CharField(max_length=1000, unique=True, verbose_name='Link'),
        ),
        migrations.AlterField(
            model_name='url',
            name='link_short',
            field=models.CharField(max_length=100, unique=True, verbose_name='Shortened Link'),
        ),
    ]
