# Generated by Django 2.1.2 on 2019-02-06 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0002_auto_20190206_1438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='link_short',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Shortened Link'),
        ),
    ]
