# Generated by Django 2.1.2 on 2019-02-07 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0003_auto_20190206_1737'),
    ]

    operations = [
        migrations.RenameField(
            model_name='url',
            old_name='count',
            new_name='count_request',
        ),
        migrations.AddField(
            model_name='url',
            name='count_clicked',
            field=models.IntegerField(default=0, verbose_name='Amount of requests'),
        ),
    ]
